language: node_js
node_js:
- '11'
addons:
  ssh_known_hosts:
  - 206.189.96.128
  - recipemug.club
branches:
  only:
  - master
env:
  global:
  - REMOTE_BACKEND_DIR=/var/backend/express-api
  - REMOTE_USER=travis
  - REMOTE_HOST=206.189.96.128
before_install:
- openssl aes-256-cbc -K $encrypted_93a4f6c5357e_key -iv $encrypted_93a4f6c5357e_iv
  -in travis_b_rsa.enc -out travis_b_rsa -d
- chmod 600 travis_b_rsa
- mv travis_b_rsa ~/.ssh/id_rsa
install:
- npm i
script:
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash .scripts/deploy.sh
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: nfL4D8H7tj/jgQs/0su9E/23jY7WV2vPkIU9aLGdCDf2R6qTpdma2+uayV6ZnffAnOgMyj6kzViGPKVYYjKVxGXyR9XtoNZNxlbSPlIXtMPLaE42rw3j2iIlKFaWV01ieoodDaNmAxqtMDCWS62yXBtSzcKt51skvaTYqqCyzdH8VFs2Mmg94UUQ5BxBolZEGoIwBpELLtr6TcKUFJOKFwzOQlRt2mBJ3K/H/xQIfjyKIg+LYxXr+b6CU66OmwkCrtd4ltQPq+UI7gqkZvISJtHoeBzm+HVjP7U4E6qYP7ARQeJG18zuHlfBQXRlLWC5jopRftthO9argUhK0Vj/j4DLInEWLITxh0OSAh6lhaosEoso4KXVzKi6IJv/nfMNrqKnI/w+SuekRnzBPA1Aymebqnga8j3IOdYcmsvIcxP6WRHco1VAj//jDmllQH5qK/8HX4BlOpMUzvCXJOAtAg8bQ9sw5lTG6SW4T+WqRcdYzCwyOemWpYOope9OQZgUSXz+TWjSVFRsyqIS+B5SYjlg6fKRSA8koENh3e2U83QmOGC8aF3Z722Bwd6KP8PXYOOoTIhN8ZA6vjUjbX2lh5bYMFsA9QyuzY6v+joxEAUNaNePGCt/4iKHeS7E84lpPVj9zWrJu9vQncXBi6CsOMUSrWZ+pHIubpjEKDrNbCU=
