version: "2"
services:
  app:
    container_name: api-recipes
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    restart: always
    command: npm  run start

  mongo:
    container_name: "mongodb"
    image: mongo:latest
    volumes:
      - ~/Desktop/mongo-data:/data/db 
    ports:
      - "27017:27017"
    hostname: mongo 
    command: 
      mongod
